from datetime import datetime
from sqlalchemy import Boolean, Column, DateTime, Float, Integer, JSON, String, Text
from sqlalchemy.orm import declarative_base, relationship
Base = declarative_base()

class MedicalDocument(Base):
    __tablename__ = "medical_documents"
    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, nullable=True)
    original_file_path = Column(String, nullable=False)
    original_file_name = Column(String, nullable=False)
    original_file_type = Column(String, nullable=False)
    file_size_bytes = Column(Integer, nullable=False)
    file_hash = Column(String, nullable=False, index=True)
    document_type = Column(String, nullable=True)
    document_type_confidence = Column(Float, nullable=True)
    test_or_report_name = Column(String, nullable=True)
    test_or_report_date = Column(String, nullable=True)
    center_name = Column(String, nullable=True)
    validation_status = Column(String, nullable=False, default="uploaded", index=True)
    verification_status = Column(String, nullable=False, default="needs_review", index=True)
    relevance_score = Column(Float, nullable=True)
    quality_score_before = Column(Float, nullable=True)
    quality_score_after = Column(Float, nullable=True)
    extraction_confidence = Column(Float, nullable=True)
    rejection_reason = Column(Text, nullable=True)
    quality_issues = Column(JSON, nullable=True)
    ocr_text = Column(Text, nullable=True)
    ocr_confidence = Column(Float, nullable=True)
    preprocessing_required = Column(Boolean, default=False)
    preprocessing_status = Column(String, nullable=True)
    preprocessed_file_path = Column(String, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    patients = relationship("DocumentPatient", back_populates="document", cascade="all, delete-orphan")
    lab_results = relationship("LabResult", back_populates="document", cascade="all, delete-orphan")
    pap_smear_reports = relationship("PapSmearReport", back_populates="document", cascade="all, delete-orphan")
    radiology_reports = relationship("RadiologyReport", back_populates="document", cascade="all, delete-orphan")
    review_tasks = relationship("ReviewTask", back_populates="document", cascade="all, delete-orphan")
